version: "3.8"

services:
  frontend-home:
    container_name: frontend-home-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - WATCHPACK_POLLING=true
    command: npm start
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
